position_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    arm_id: panda

cartesian_velocity_example_controller:
    type: panda_robot_controllers/CartesianVelocityExampleController
    arm_id: panda

cartesian_pose_example_controller:
    type: panda_robot_controllers/CartesianPoseExampleController
    arm_id: panda

joint_group_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

joint_group_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    state_publish_rate: 25

effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  gains:
      panda_joint1: {p: 50,  i: 0., d: 14.1421356}
      panda_joint2: {p: 50,  i: 0., d: 14.1421356}
      panda_joint3: {p: 50,  i: 0., d: 14.1421356}
      panda_joint4: {p: 50,  i: 0., d: 14.1421356}
      panda_joint5: {p: 50,  i: 0., d: 14.1421356}
      panda_joint6: {p: 50,  i: 0., d: 14.1421356}
      panda_joint7: {p: 50,  i: 0., d: 14.1421356}

effort_joint_group_position_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  panda_joint1:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint2:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint3:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint4:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint5:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint6:
    pid: {p: 50, i: 0, d: 14.1421356}
  panda_joint7:
    pid: {p: 50, i: 0, d: 14.1421356}
