position_joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    arm_id: panda

cartesian_velocity_example_controller:
    type: panda_robot_controllers/CartesianVelocityExampleController
    arm_id: panda

cartesian_pose_example_controller:
    type: panda_robot_controllers/CartesianPoseExampleController
    arm_id: panda

joint_group_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
<<<<<<< HEAD

=======
>>>>>>> 06e8e7c905d0adf1e982fe92774bd8d737e98a40
